//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevGUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressMap
    {
        public int AddressMapID { get; set; }
        public int NameID { get; set; }
        public int AddressID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Name Name { get; set; }
    }
}
