//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevGUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public string CreditCardNum { get; set; }
        public string CSCNum { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime InitialDate { get; set; }
        public bool Active { get; set; }
    }
}
