//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevGUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public Nullable<int> NameID { get; set; }
    
        public virtual Name Name { get; set; }
    }
}
